name: Il2Cpp Dumper LQM

on:
  workflow_dispatch:

jobs:
  decompile:
    runs-on: ubuntu-latest

    steps:
      - name: Tạo thư mục
        run: mkdir -p work/output work/DumperTool work/GameData

      - name: Tải Il2CppDumper (Link Cứng)
        run: |
          cd work
          # Tải thẳng bản v6.7.40 chuẩn nhất
          curl -L -o dumper.zip "https://github.com/Perfare/Il2CppDumper/releases/download/v6.7.40/Il2CppDumper-v6.7.40.zip"
          unzip -q dumper.zip -d DumperTool

      - name: Tải Game Data từ Release của bác
        run: |
          cd work
          curl -L -o data.zip "https://github.com/Mobimi/codespace/releases/download/Data/Data.zip"
          unzip -o -q data.zip -d GameData
          echo "--- Danh sách file trong GameData ---"
          find GameData -type f

      - name: Chạy Dumper
        run: |
          cd work
          # Tự động tìm file
          UNITY=$(find GameData -type f -name "UnityFramework" | head -n 1)
          META=$(find GameData -type f -name "global-metadata.dat" | head -n 1)
          
          echo "Dùng Unity: $UNITY"
          echo "Dùng Metadata: $META"
          
          if [ -z "$UNITY" ] || [ -z "$META" ]; then
            echo "LỖI: Không thấy file trong Zip!"
            exit 1
          fi

          # Thực hiện dịch ngược
          dotnet DumperTool/Il2CppDumper.dll "$UNITY" "$META" output/

      - name: Trả hàng Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: LQM-Offsets-Json
          path: work/output/
          if-no-files-found: error
